// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koo-arch/servant-trait-filter-backend/ent/moralalignment"
	"github.com/koo-arch/servant-trait-filter-backend/ent/predicate"
)

// MoralAlignmentDelete is the builder for deleting a MoralAlignment entity.
type MoralAlignmentDelete struct {
	config
	hooks    []Hook
	mutation *MoralAlignmentMutation
}

// Where appends a list predicates to the MoralAlignmentDelete builder.
func (mad *MoralAlignmentDelete) Where(ps ...predicate.MoralAlignment) *MoralAlignmentDelete {
	mad.mutation.Where(ps...)
	return mad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mad *MoralAlignmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mad.sqlExec, mad.mutation, mad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mad *MoralAlignmentDelete) ExecX(ctx context.Context) int {
	n, err := mad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mad *MoralAlignmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(moralalignment.Table, sqlgraph.NewFieldSpec(moralalignment.FieldID, field.TypeInt))
	if ps := mad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mad.mutation.done = true
	return affected, err
}

// MoralAlignmentDeleteOne is the builder for deleting a single MoralAlignment entity.
type MoralAlignmentDeleteOne struct {
	mad *MoralAlignmentDelete
}

// Where appends a list predicates to the MoralAlignmentDelete builder.
func (mado *MoralAlignmentDeleteOne) Where(ps ...predicate.MoralAlignment) *MoralAlignmentDeleteOne {
	mado.mad.mutation.Where(ps...)
	return mado
}

// Exec executes the deletion query.
func (mado *MoralAlignmentDeleteOne) Exec(ctx context.Context) error {
	n, err := mado.mad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{moralalignment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mado *MoralAlignmentDeleteOne) ExecX(ctx context.Context) {
	if err := mado.Exec(ctx); err != nil {
		panic(err)
	}
}
