// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koo-arch/servant-trait-filter-backend/ent/ascension"
	"github.com/koo-arch/servant-trait-filter-backend/ent/moralalignment"
	"github.com/koo-arch/servant-trait-filter-backend/ent/predicate"
)

// MoralAlignmentUpdate is the builder for updating MoralAlignment entities.
type MoralAlignmentUpdate struct {
	config
	hooks    []Hook
	mutation *MoralAlignmentMutation
}

// Where appends a list predicates to the MoralAlignmentUpdate builder.
func (mau *MoralAlignmentUpdate) Where(ps ...predicate.MoralAlignment) *MoralAlignmentUpdate {
	mau.mutation.Where(ps...)
	return mau
}

// SetUpdatedAt sets the "updated_at" field.
func (mau *MoralAlignmentUpdate) SetUpdatedAt(t time.Time) *MoralAlignmentUpdate {
	mau.mutation.SetUpdatedAt(t)
	return mau
}

// SetNameEn sets the "name_en" field.
func (mau *MoralAlignmentUpdate) SetNameEn(s string) *MoralAlignmentUpdate {
	mau.mutation.SetNameEn(s)
	return mau
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (mau *MoralAlignmentUpdate) SetNillableNameEn(s *string) *MoralAlignmentUpdate {
	if s != nil {
		mau.SetNameEn(*s)
	}
	return mau
}

// SetNameJa sets the "name_ja" field.
func (mau *MoralAlignmentUpdate) SetNameJa(s string) *MoralAlignmentUpdate {
	mau.mutation.SetNameJa(s)
	return mau
}

// SetNillableNameJa sets the "name_ja" field if the given value is not nil.
func (mau *MoralAlignmentUpdate) SetNillableNameJa(s *string) *MoralAlignmentUpdate {
	if s != nil {
		mau.SetNameJa(*s)
	}
	return mau
}

// ClearNameJa clears the value of the "name_ja" field.
func (mau *MoralAlignmentUpdate) ClearNameJa() *MoralAlignmentUpdate {
	mau.mutation.ClearNameJa()
	return mau
}

// AddAscensionIDs adds the "ascensions" edge to the Ascension entity by IDs.
func (mau *MoralAlignmentUpdate) AddAscensionIDs(ids ...int) *MoralAlignmentUpdate {
	mau.mutation.AddAscensionIDs(ids...)
	return mau
}

// AddAscensions adds the "ascensions" edges to the Ascension entity.
func (mau *MoralAlignmentUpdate) AddAscensions(a ...*Ascension) *MoralAlignmentUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return mau.AddAscensionIDs(ids...)
}

// Mutation returns the MoralAlignmentMutation object of the builder.
func (mau *MoralAlignmentUpdate) Mutation() *MoralAlignmentMutation {
	return mau.mutation
}

// ClearAscensions clears all "ascensions" edges to the Ascension entity.
func (mau *MoralAlignmentUpdate) ClearAscensions() *MoralAlignmentUpdate {
	mau.mutation.ClearAscensions()
	return mau
}

// RemoveAscensionIDs removes the "ascensions" edge to Ascension entities by IDs.
func (mau *MoralAlignmentUpdate) RemoveAscensionIDs(ids ...int) *MoralAlignmentUpdate {
	mau.mutation.RemoveAscensionIDs(ids...)
	return mau
}

// RemoveAscensions removes "ascensions" edges to Ascension entities.
func (mau *MoralAlignmentUpdate) RemoveAscensions(a ...*Ascension) *MoralAlignmentUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return mau.RemoveAscensionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mau *MoralAlignmentUpdate) Save(ctx context.Context) (int, error) {
	mau.defaults()
	return withHooks(ctx, mau.sqlSave, mau.mutation, mau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mau *MoralAlignmentUpdate) SaveX(ctx context.Context) int {
	affected, err := mau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mau *MoralAlignmentUpdate) Exec(ctx context.Context) error {
	_, err := mau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mau *MoralAlignmentUpdate) ExecX(ctx context.Context) {
	if err := mau.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mau *MoralAlignmentUpdate) defaults() {
	if _, ok := mau.mutation.UpdatedAt(); !ok {
		v := moralalignment.UpdateDefaultUpdatedAt()
		mau.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mau *MoralAlignmentUpdate) check() error {
	if v, ok := mau.mutation.NameEn(); ok {
		if err := moralalignment.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "MoralAlignment.name_en": %w`, err)}
		}
	}
	return nil
}

func (mau *MoralAlignmentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(moralalignment.Table, moralalignment.Columns, sqlgraph.NewFieldSpec(moralalignment.FieldID, field.TypeInt))
	if ps := mau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mau.mutation.UpdatedAt(); ok {
		_spec.SetField(moralalignment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := mau.mutation.NameEn(); ok {
		_spec.SetField(moralalignment.FieldNameEn, field.TypeString, value)
	}
	if value, ok := mau.mutation.NameJa(); ok {
		_spec.SetField(moralalignment.FieldNameJa, field.TypeString, value)
	}
	if mau.mutation.NameJaCleared() {
		_spec.ClearField(moralalignment.FieldNameJa, field.TypeString)
	}
	if mau.mutation.AscensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   moralalignment.AscensionsTable,
			Columns: []string{moralalignment.AscensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ascension.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mau.mutation.RemovedAscensionsIDs(); len(nodes) > 0 && !mau.mutation.AscensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   moralalignment.AscensionsTable,
			Columns: []string{moralalignment.AscensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ascension.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mau.mutation.AscensionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   moralalignment.AscensionsTable,
			Columns: []string{moralalignment.AscensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ascension.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{moralalignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mau.mutation.done = true
	return n, nil
}

// MoralAlignmentUpdateOne is the builder for updating a single MoralAlignment entity.
type MoralAlignmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MoralAlignmentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (mauo *MoralAlignmentUpdateOne) SetUpdatedAt(t time.Time) *MoralAlignmentUpdateOne {
	mauo.mutation.SetUpdatedAt(t)
	return mauo
}

// SetNameEn sets the "name_en" field.
func (mauo *MoralAlignmentUpdateOne) SetNameEn(s string) *MoralAlignmentUpdateOne {
	mauo.mutation.SetNameEn(s)
	return mauo
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (mauo *MoralAlignmentUpdateOne) SetNillableNameEn(s *string) *MoralAlignmentUpdateOne {
	if s != nil {
		mauo.SetNameEn(*s)
	}
	return mauo
}

// SetNameJa sets the "name_ja" field.
func (mauo *MoralAlignmentUpdateOne) SetNameJa(s string) *MoralAlignmentUpdateOne {
	mauo.mutation.SetNameJa(s)
	return mauo
}

// SetNillableNameJa sets the "name_ja" field if the given value is not nil.
func (mauo *MoralAlignmentUpdateOne) SetNillableNameJa(s *string) *MoralAlignmentUpdateOne {
	if s != nil {
		mauo.SetNameJa(*s)
	}
	return mauo
}

// ClearNameJa clears the value of the "name_ja" field.
func (mauo *MoralAlignmentUpdateOne) ClearNameJa() *MoralAlignmentUpdateOne {
	mauo.mutation.ClearNameJa()
	return mauo
}

// AddAscensionIDs adds the "ascensions" edge to the Ascension entity by IDs.
func (mauo *MoralAlignmentUpdateOne) AddAscensionIDs(ids ...int) *MoralAlignmentUpdateOne {
	mauo.mutation.AddAscensionIDs(ids...)
	return mauo
}

// AddAscensions adds the "ascensions" edges to the Ascension entity.
func (mauo *MoralAlignmentUpdateOne) AddAscensions(a ...*Ascension) *MoralAlignmentUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return mauo.AddAscensionIDs(ids...)
}

// Mutation returns the MoralAlignmentMutation object of the builder.
func (mauo *MoralAlignmentUpdateOne) Mutation() *MoralAlignmentMutation {
	return mauo.mutation
}

// ClearAscensions clears all "ascensions" edges to the Ascension entity.
func (mauo *MoralAlignmentUpdateOne) ClearAscensions() *MoralAlignmentUpdateOne {
	mauo.mutation.ClearAscensions()
	return mauo
}

// RemoveAscensionIDs removes the "ascensions" edge to Ascension entities by IDs.
func (mauo *MoralAlignmentUpdateOne) RemoveAscensionIDs(ids ...int) *MoralAlignmentUpdateOne {
	mauo.mutation.RemoveAscensionIDs(ids...)
	return mauo
}

// RemoveAscensions removes "ascensions" edges to Ascension entities.
func (mauo *MoralAlignmentUpdateOne) RemoveAscensions(a ...*Ascension) *MoralAlignmentUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return mauo.RemoveAscensionIDs(ids...)
}

// Where appends a list predicates to the MoralAlignmentUpdate builder.
func (mauo *MoralAlignmentUpdateOne) Where(ps ...predicate.MoralAlignment) *MoralAlignmentUpdateOne {
	mauo.mutation.Where(ps...)
	return mauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mauo *MoralAlignmentUpdateOne) Select(field string, fields ...string) *MoralAlignmentUpdateOne {
	mauo.fields = append([]string{field}, fields...)
	return mauo
}

// Save executes the query and returns the updated MoralAlignment entity.
func (mauo *MoralAlignmentUpdateOne) Save(ctx context.Context) (*MoralAlignment, error) {
	mauo.defaults()
	return withHooks(ctx, mauo.sqlSave, mauo.mutation, mauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mauo *MoralAlignmentUpdateOne) SaveX(ctx context.Context) *MoralAlignment {
	node, err := mauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mauo *MoralAlignmentUpdateOne) Exec(ctx context.Context) error {
	_, err := mauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mauo *MoralAlignmentUpdateOne) ExecX(ctx context.Context) {
	if err := mauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mauo *MoralAlignmentUpdateOne) defaults() {
	if _, ok := mauo.mutation.UpdatedAt(); !ok {
		v := moralalignment.UpdateDefaultUpdatedAt()
		mauo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mauo *MoralAlignmentUpdateOne) check() error {
	if v, ok := mauo.mutation.NameEn(); ok {
		if err := moralalignment.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "MoralAlignment.name_en": %w`, err)}
		}
	}
	return nil
}

func (mauo *MoralAlignmentUpdateOne) sqlSave(ctx context.Context) (_node *MoralAlignment, err error) {
	if err := mauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(moralalignment.Table, moralalignment.Columns, sqlgraph.NewFieldSpec(moralalignment.FieldID, field.TypeInt))
	id, ok := mauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MoralAlignment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moralalignment.FieldID)
		for _, f := range fields {
			if !moralalignment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != moralalignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mauo.mutation.UpdatedAt(); ok {
		_spec.SetField(moralalignment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := mauo.mutation.NameEn(); ok {
		_spec.SetField(moralalignment.FieldNameEn, field.TypeString, value)
	}
	if value, ok := mauo.mutation.NameJa(); ok {
		_spec.SetField(moralalignment.FieldNameJa, field.TypeString, value)
	}
	if mauo.mutation.NameJaCleared() {
		_spec.ClearField(moralalignment.FieldNameJa, field.TypeString)
	}
	if mauo.mutation.AscensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   moralalignment.AscensionsTable,
			Columns: []string{moralalignment.AscensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ascension.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mauo.mutation.RemovedAscensionsIDs(); len(nodes) > 0 && !mauo.mutation.AscensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   moralalignment.AscensionsTable,
			Columns: []string{moralalignment.AscensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ascension.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mauo.mutation.AscensionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   moralalignment.AscensionsTable,
			Columns: []string{moralalignment.AscensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ascension.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MoralAlignment{config: mauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{moralalignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mauo.mutation.done = true
	return _node, nil
}
