// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koo-arch/servant-trait-filter-backend/ent/moralalignment"
	"github.com/koo-arch/servant-trait-filter-backend/ent/predicate"
	"github.com/koo-arch/servant-trait-filter-backend/ent/servant"
)

// MoralAlignmentQuery is the builder for querying MoralAlignment entities.
type MoralAlignmentQuery struct {
	config
	ctx          *QueryContext
	order        []moralalignment.OrderOption
	inters       []Interceptor
	predicates   []predicate.MoralAlignment
	withServants *ServantQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MoralAlignmentQuery builder.
func (maq *MoralAlignmentQuery) Where(ps ...predicate.MoralAlignment) *MoralAlignmentQuery {
	maq.predicates = append(maq.predicates, ps...)
	return maq
}

// Limit the number of records to be returned by this query.
func (maq *MoralAlignmentQuery) Limit(limit int) *MoralAlignmentQuery {
	maq.ctx.Limit = &limit
	return maq
}

// Offset to start from.
func (maq *MoralAlignmentQuery) Offset(offset int) *MoralAlignmentQuery {
	maq.ctx.Offset = &offset
	return maq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (maq *MoralAlignmentQuery) Unique(unique bool) *MoralAlignmentQuery {
	maq.ctx.Unique = &unique
	return maq
}

// Order specifies how the records should be ordered.
func (maq *MoralAlignmentQuery) Order(o ...moralalignment.OrderOption) *MoralAlignmentQuery {
	maq.order = append(maq.order, o...)
	return maq
}

// QueryServants chains the current query on the "servants" edge.
func (maq *MoralAlignmentQuery) QueryServants() *ServantQuery {
	query := (&ServantClient{config: maq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := maq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := maq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(moralalignment.Table, moralalignment.FieldID, selector),
			sqlgraph.To(servant.Table, servant.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, moralalignment.ServantsTable, moralalignment.ServantsColumn),
		)
		fromU = sqlgraph.SetNeighbors(maq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MoralAlignment entity from the query.
// Returns a *NotFoundError when no MoralAlignment was found.
func (maq *MoralAlignmentQuery) First(ctx context.Context) (*MoralAlignment, error) {
	nodes, err := maq.Limit(1).All(setContextOp(ctx, maq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{moralalignment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (maq *MoralAlignmentQuery) FirstX(ctx context.Context) *MoralAlignment {
	node, err := maq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MoralAlignment ID from the query.
// Returns a *NotFoundError when no MoralAlignment ID was found.
func (maq *MoralAlignmentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = maq.Limit(1).IDs(setContextOp(ctx, maq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{moralalignment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (maq *MoralAlignmentQuery) FirstIDX(ctx context.Context) int {
	id, err := maq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MoralAlignment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MoralAlignment entity is found.
// Returns a *NotFoundError when no MoralAlignment entities are found.
func (maq *MoralAlignmentQuery) Only(ctx context.Context) (*MoralAlignment, error) {
	nodes, err := maq.Limit(2).All(setContextOp(ctx, maq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{moralalignment.Label}
	default:
		return nil, &NotSingularError{moralalignment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (maq *MoralAlignmentQuery) OnlyX(ctx context.Context) *MoralAlignment {
	node, err := maq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MoralAlignment ID in the query.
// Returns a *NotSingularError when more than one MoralAlignment ID is found.
// Returns a *NotFoundError when no entities are found.
func (maq *MoralAlignmentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = maq.Limit(2).IDs(setContextOp(ctx, maq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{moralalignment.Label}
	default:
		err = &NotSingularError{moralalignment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (maq *MoralAlignmentQuery) OnlyIDX(ctx context.Context) int {
	id, err := maq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MoralAlignments.
func (maq *MoralAlignmentQuery) All(ctx context.Context) ([]*MoralAlignment, error) {
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryAll)
	if err := maq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MoralAlignment, *MoralAlignmentQuery]()
	return withInterceptors[[]*MoralAlignment](ctx, maq, qr, maq.inters)
}

// AllX is like All, but panics if an error occurs.
func (maq *MoralAlignmentQuery) AllX(ctx context.Context) []*MoralAlignment {
	nodes, err := maq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MoralAlignment IDs.
func (maq *MoralAlignmentQuery) IDs(ctx context.Context) (ids []int, err error) {
	if maq.ctx.Unique == nil && maq.path != nil {
		maq.Unique(true)
	}
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryIDs)
	if err = maq.Select(moralalignment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (maq *MoralAlignmentQuery) IDsX(ctx context.Context) []int {
	ids, err := maq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (maq *MoralAlignmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryCount)
	if err := maq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, maq, querierCount[*MoralAlignmentQuery](), maq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (maq *MoralAlignmentQuery) CountX(ctx context.Context) int {
	count, err := maq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (maq *MoralAlignmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryExist)
	switch _, err := maq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (maq *MoralAlignmentQuery) ExistX(ctx context.Context) bool {
	exist, err := maq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MoralAlignmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (maq *MoralAlignmentQuery) Clone() *MoralAlignmentQuery {
	if maq == nil {
		return nil
	}
	return &MoralAlignmentQuery{
		config:       maq.config,
		ctx:          maq.ctx.Clone(),
		order:        append([]moralalignment.OrderOption{}, maq.order...),
		inters:       append([]Interceptor{}, maq.inters...),
		predicates:   append([]predicate.MoralAlignment{}, maq.predicates...),
		withServants: maq.withServants.Clone(),
		// clone intermediate query.
		sql:  maq.sql.Clone(),
		path: maq.path,
	}
}

// WithServants tells the query-builder to eager-load the nodes that are connected to
// the "servants" edge. The optional arguments are used to configure the query builder of the edge.
func (maq *MoralAlignmentQuery) WithServants(opts ...func(*ServantQuery)) *MoralAlignmentQuery {
	query := (&ServantClient{config: maq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	maq.withServants = query
	return maq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MoralAlignment.Query().
//		GroupBy(moralalignment.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (maq *MoralAlignmentQuery) GroupBy(field string, fields ...string) *MoralAlignmentGroupBy {
	maq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MoralAlignmentGroupBy{build: maq}
	grbuild.flds = &maq.ctx.Fields
	grbuild.label = moralalignment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.MoralAlignment.Query().
//		Select(moralalignment.FieldCreatedAt).
//		Scan(ctx, &v)
func (maq *MoralAlignmentQuery) Select(fields ...string) *MoralAlignmentSelect {
	maq.ctx.Fields = append(maq.ctx.Fields, fields...)
	sbuild := &MoralAlignmentSelect{MoralAlignmentQuery: maq}
	sbuild.label = moralalignment.Label
	sbuild.flds, sbuild.scan = &maq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MoralAlignmentSelect configured with the given aggregations.
func (maq *MoralAlignmentQuery) Aggregate(fns ...AggregateFunc) *MoralAlignmentSelect {
	return maq.Select().Aggregate(fns...)
}

func (maq *MoralAlignmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range maq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, maq); err != nil {
				return err
			}
		}
	}
	for _, f := range maq.ctx.Fields {
		if !moralalignment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if maq.path != nil {
		prev, err := maq.path(ctx)
		if err != nil {
			return err
		}
		maq.sql = prev
	}
	return nil
}

func (maq *MoralAlignmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MoralAlignment, error) {
	var (
		nodes       = []*MoralAlignment{}
		_spec       = maq.querySpec()
		loadedTypes = [1]bool{
			maq.withServants != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MoralAlignment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MoralAlignment{config: maq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, maq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := maq.withServants; query != nil {
		if err := maq.loadServants(ctx, query, nodes,
			func(n *MoralAlignment) { n.Edges.Servants = []*Servant{} },
			func(n *MoralAlignment, e *Servant) { n.Edges.Servants = append(n.Edges.Servants, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (maq *MoralAlignmentQuery) loadServants(ctx context.Context, query *ServantQuery, nodes []*MoralAlignment, init func(*MoralAlignment), assign func(*MoralAlignment, *Servant)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*MoralAlignment)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(servant.FieldMoralAlignmentID)
	}
	query.Where(predicate.Servant(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(moralalignment.ServantsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MoralAlignmentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "moral_alignment_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (maq *MoralAlignmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := maq.querySpec()
	_spec.Node.Columns = maq.ctx.Fields
	if len(maq.ctx.Fields) > 0 {
		_spec.Unique = maq.ctx.Unique != nil && *maq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, maq.driver, _spec)
}

func (maq *MoralAlignmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(moralalignment.Table, moralalignment.Columns, sqlgraph.NewFieldSpec(moralalignment.FieldID, field.TypeInt))
	_spec.From = maq.sql
	if unique := maq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if maq.path != nil {
		_spec.Unique = true
	}
	if fields := maq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moralalignment.FieldID)
		for i := range fields {
			if fields[i] != moralalignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := maq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := maq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := maq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := maq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (maq *MoralAlignmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(maq.driver.Dialect())
	t1 := builder.Table(moralalignment.Table)
	columns := maq.ctx.Fields
	if len(columns) == 0 {
		columns = moralalignment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if maq.sql != nil {
		selector = maq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if maq.ctx.Unique != nil && *maq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range maq.predicates {
		p(selector)
	}
	for _, p := range maq.order {
		p(selector)
	}
	if offset := maq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := maq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MoralAlignmentGroupBy is the group-by builder for MoralAlignment entities.
type MoralAlignmentGroupBy struct {
	selector
	build *MoralAlignmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (magb *MoralAlignmentGroupBy) Aggregate(fns ...AggregateFunc) *MoralAlignmentGroupBy {
	magb.fns = append(magb.fns, fns...)
	return magb
}

// Scan applies the selector query and scans the result into the given value.
func (magb *MoralAlignmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, magb.build.ctx, ent.OpQueryGroupBy)
	if err := magb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MoralAlignmentQuery, *MoralAlignmentGroupBy](ctx, magb.build, magb, magb.build.inters, v)
}

func (magb *MoralAlignmentGroupBy) sqlScan(ctx context.Context, root *MoralAlignmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(magb.fns))
	for _, fn := range magb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*magb.flds)+len(magb.fns))
		for _, f := range *magb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*magb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := magb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MoralAlignmentSelect is the builder for selecting fields of MoralAlignment entities.
type MoralAlignmentSelect struct {
	*MoralAlignmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mas *MoralAlignmentSelect) Aggregate(fns ...AggregateFunc) *MoralAlignmentSelect {
	mas.fns = append(mas.fns, fns...)
	return mas
}

// Scan applies the selector query and scans the result into the given value.
func (mas *MoralAlignmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mas.ctx, ent.OpQuerySelect)
	if err := mas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MoralAlignmentQuery, *MoralAlignmentSelect](ctx, mas.MoralAlignmentQuery, mas, mas.inters, v)
}

func (mas *MoralAlignmentSelect) sqlScan(ctx context.Context, root *MoralAlignmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mas.fns))
	for _, fn := range mas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
