// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koo-arch/servant-trait-filter-backend/ent/moralalignment"
	"github.com/koo-arch/servant-trait-filter-backend/ent/servant"
)

// MoralAlignmentCreate is the builder for creating a MoralAlignment entity.
type MoralAlignmentCreate struct {
	config
	mutation *MoralAlignmentMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (mac *MoralAlignmentCreate) SetCreatedAt(t time.Time) *MoralAlignmentCreate {
	mac.mutation.SetCreatedAt(t)
	return mac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mac *MoralAlignmentCreate) SetNillableCreatedAt(t *time.Time) *MoralAlignmentCreate {
	if t != nil {
		mac.SetCreatedAt(*t)
	}
	return mac
}

// SetUpdatedAt sets the "updated_at" field.
func (mac *MoralAlignmentCreate) SetUpdatedAt(t time.Time) *MoralAlignmentCreate {
	mac.mutation.SetUpdatedAt(t)
	return mac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mac *MoralAlignmentCreate) SetNillableUpdatedAt(t *time.Time) *MoralAlignmentCreate {
	if t != nil {
		mac.SetUpdatedAt(*t)
	}
	return mac
}

// SetNameEn sets the "name_en" field.
func (mac *MoralAlignmentCreate) SetNameEn(s string) *MoralAlignmentCreate {
	mac.mutation.SetNameEn(s)
	return mac
}

// SetNameJa sets the "name_ja" field.
func (mac *MoralAlignmentCreate) SetNameJa(s string) *MoralAlignmentCreate {
	mac.mutation.SetNameJa(s)
	return mac
}

// AddServantIDs adds the "servants" edge to the Servant entity by IDs.
func (mac *MoralAlignmentCreate) AddServantIDs(ids ...int) *MoralAlignmentCreate {
	mac.mutation.AddServantIDs(ids...)
	return mac
}

// AddServants adds the "servants" edges to the Servant entity.
func (mac *MoralAlignmentCreate) AddServants(s ...*Servant) *MoralAlignmentCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return mac.AddServantIDs(ids...)
}

// Mutation returns the MoralAlignmentMutation object of the builder.
func (mac *MoralAlignmentCreate) Mutation() *MoralAlignmentMutation {
	return mac.mutation
}

// Save creates the MoralAlignment in the database.
func (mac *MoralAlignmentCreate) Save(ctx context.Context) (*MoralAlignment, error) {
	mac.defaults()
	return withHooks(ctx, mac.sqlSave, mac.mutation, mac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mac *MoralAlignmentCreate) SaveX(ctx context.Context) *MoralAlignment {
	v, err := mac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mac *MoralAlignmentCreate) Exec(ctx context.Context) error {
	_, err := mac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mac *MoralAlignmentCreate) ExecX(ctx context.Context) {
	if err := mac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mac *MoralAlignmentCreate) defaults() {
	if _, ok := mac.mutation.CreatedAt(); !ok {
		v := moralalignment.DefaultCreatedAt()
		mac.mutation.SetCreatedAt(v)
	}
	if _, ok := mac.mutation.UpdatedAt(); !ok {
		v := moralalignment.DefaultUpdatedAt()
		mac.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mac *MoralAlignmentCreate) check() error {
	if _, ok := mac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MoralAlignment.created_at"`)}
	}
	if _, ok := mac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MoralAlignment.updated_at"`)}
	}
	if _, ok := mac.mutation.NameEn(); !ok {
		return &ValidationError{Name: "name_en", err: errors.New(`ent: missing required field "MoralAlignment.name_en"`)}
	}
	if v, ok := mac.mutation.NameEn(); ok {
		if err := moralalignment.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "MoralAlignment.name_en": %w`, err)}
		}
	}
	if _, ok := mac.mutation.NameJa(); !ok {
		return &ValidationError{Name: "name_ja", err: errors.New(`ent: missing required field "MoralAlignment.name_ja"`)}
	}
	return nil
}

func (mac *MoralAlignmentCreate) sqlSave(ctx context.Context) (*MoralAlignment, error) {
	if err := mac.check(); err != nil {
		return nil, err
	}
	_node, _spec := mac.createSpec()
	if err := sqlgraph.CreateNode(ctx, mac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mac.mutation.id = &_node.ID
	mac.mutation.done = true
	return _node, nil
}

func (mac *MoralAlignmentCreate) createSpec() (*MoralAlignment, *sqlgraph.CreateSpec) {
	var (
		_node = &MoralAlignment{config: mac.config}
		_spec = sqlgraph.NewCreateSpec(moralalignment.Table, sqlgraph.NewFieldSpec(moralalignment.FieldID, field.TypeInt))
	)
	if value, ok := mac.mutation.CreatedAt(); ok {
		_spec.SetField(moralalignment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mac.mutation.UpdatedAt(); ok {
		_spec.SetField(moralalignment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := mac.mutation.NameEn(); ok {
		_spec.SetField(moralalignment.FieldNameEn, field.TypeString, value)
		_node.NameEn = value
	}
	if value, ok := mac.mutation.NameJa(); ok {
		_spec.SetField(moralalignment.FieldNameJa, field.TypeString, value)
		_node.NameJa = value
	}
	if nodes := mac.mutation.ServantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   moralalignment.ServantsTable,
			Columns: []string{moralalignment.ServantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MoralAlignmentCreateBulk is the builder for creating many MoralAlignment entities in bulk.
type MoralAlignmentCreateBulk struct {
	config
	err      error
	builders []*MoralAlignmentCreate
}

// Save creates the MoralAlignment entities in the database.
func (macb *MoralAlignmentCreateBulk) Save(ctx context.Context) ([]*MoralAlignment, error) {
	if macb.err != nil {
		return nil, macb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(macb.builders))
	nodes := make([]*MoralAlignment, len(macb.builders))
	mutators := make([]Mutator, len(macb.builders))
	for i := range macb.builders {
		func(i int, root context.Context) {
			builder := macb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MoralAlignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, macb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, macb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, macb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (macb *MoralAlignmentCreateBulk) SaveX(ctx context.Context) []*MoralAlignment {
	v, err := macb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (macb *MoralAlignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := macb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (macb *MoralAlignmentCreateBulk) ExecX(ctx context.Context) {
	if err := macb.Exec(ctx); err != nil {
		panic(err)
	}
}
