// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koo-arch/servant-trait-filter-backend/ent/orderalignment"
	"github.com/koo-arch/servant-trait-filter-backend/ent/predicate"
)

// OrderAlignmentDelete is the builder for deleting a OrderAlignment entity.
type OrderAlignmentDelete struct {
	config
	hooks    []Hook
	mutation *OrderAlignmentMutation
}

// Where appends a list predicates to the OrderAlignmentDelete builder.
func (oad *OrderAlignmentDelete) Where(ps ...predicate.OrderAlignment) *OrderAlignmentDelete {
	oad.mutation.Where(ps...)
	return oad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (oad *OrderAlignmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, oad.sqlExec, oad.mutation, oad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (oad *OrderAlignmentDelete) ExecX(ctx context.Context) int {
	n, err := oad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (oad *OrderAlignmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orderalignment.Table, sqlgraph.NewFieldSpec(orderalignment.FieldID, field.TypeInt))
	if ps := oad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, oad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	oad.mutation.done = true
	return affected, err
}

// OrderAlignmentDeleteOne is the builder for deleting a single OrderAlignment entity.
type OrderAlignmentDeleteOne struct {
	oad *OrderAlignmentDelete
}

// Where appends a list predicates to the OrderAlignmentDelete builder.
func (oado *OrderAlignmentDeleteOne) Where(ps ...predicate.OrderAlignment) *OrderAlignmentDeleteOne {
	oado.oad.mutation.Where(ps...)
	return oado
}

// Exec executes the deletion query.
func (oado *OrderAlignmentDeleteOne) Exec(ctx context.Context) error {
	n, err := oado.oad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orderalignment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (oado *OrderAlignmentDeleteOne) ExecX(ctx context.Context) {
	if err := oado.Exec(ctx); err != nil {
		panic(err)
	}
}
