// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/koo-arch/servant-trait-filter-backend/ent/attribute"
	"github.com/koo-arch/servant-trait-filter-backend/ent/class"
	"github.com/koo-arch/servant-trait-filter-backend/ent/moralalignment"
	"github.com/koo-arch/servant-trait-filter-backend/ent/orderalignment"
	"github.com/koo-arch/servant-trait-filter-backend/ent/schema"
	"github.com/koo-arch/servant-trait-filter-backend/ent/servant"
	"github.com/koo-arch/servant-trait-filter-backend/ent/trait"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attributeMixin := schema.Attribute{}.Mixin()
	attributeMixinFields0 := attributeMixin[0].Fields()
	_ = attributeMixinFields0
	attributeMixinFields1 := attributeMixin[1].Fields()
	_ = attributeMixinFields1
	attributeFields := schema.Attribute{}.Fields()
	_ = attributeFields
	// attributeDescCreatedAt is the schema descriptor for created_at field.
	attributeDescCreatedAt := attributeMixinFields0[0].Descriptor()
	// attribute.DefaultCreatedAt holds the default value on creation for the created_at field.
	attribute.DefaultCreatedAt = attributeDescCreatedAt.Default.(func() time.Time)
	// attributeDescUpdatedAt is the schema descriptor for updated_at field.
	attributeDescUpdatedAt := attributeMixinFields0[1].Descriptor()
	// attribute.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	attribute.DefaultUpdatedAt = attributeDescUpdatedAt.Default.(func() time.Time)
	// attribute.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	attribute.UpdateDefaultUpdatedAt = attributeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// attributeDescNameEn is the schema descriptor for name_en field.
	attributeDescNameEn := attributeMixinFields1[0].Descriptor()
	// attribute.NameEnValidator is a validator for the "name_en" field. It is called by the builders before save.
	attribute.NameEnValidator = attributeDescNameEn.Validators[0].(func(string) error)
	// attributeDescID is the schema descriptor for id field.
	attributeDescID := attributeFields[0].Descriptor()
	// attribute.IDValidator is a validator for the "id" field. It is called by the builders before save.
	attribute.IDValidator = attributeDescID.Validators[0].(func(int) error)
	classMixin := schema.Class{}.Mixin()
	classMixinFields0 := classMixin[0].Fields()
	_ = classMixinFields0
	classMixinFields1 := classMixin[1].Fields()
	_ = classMixinFields1
	classFields := schema.Class{}.Fields()
	_ = classFields
	// classDescCreatedAt is the schema descriptor for created_at field.
	classDescCreatedAt := classMixinFields0[0].Descriptor()
	// class.DefaultCreatedAt holds the default value on creation for the created_at field.
	class.DefaultCreatedAt = classDescCreatedAt.Default.(func() time.Time)
	// classDescUpdatedAt is the schema descriptor for updated_at field.
	classDescUpdatedAt := classMixinFields0[1].Descriptor()
	// class.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	class.DefaultUpdatedAt = classDescUpdatedAt.Default.(func() time.Time)
	// class.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	class.UpdateDefaultUpdatedAt = classDescUpdatedAt.UpdateDefault.(func() time.Time)
	// classDescNameEn is the schema descriptor for name_en field.
	classDescNameEn := classMixinFields1[0].Descriptor()
	// class.NameEnValidator is a validator for the "name_en" field. It is called by the builders before save.
	class.NameEnValidator = classDescNameEn.Validators[0].(func(string) error)
	// classDescID is the schema descriptor for id field.
	classDescID := classFields[0].Descriptor()
	// class.IDValidator is a validator for the "id" field. It is called by the builders before save.
	class.IDValidator = classDescID.Validators[0].(func(int) error)
	moralalignmentMixin := schema.MoralAlignment{}.Mixin()
	moralalignmentMixinFields0 := moralalignmentMixin[0].Fields()
	_ = moralalignmentMixinFields0
	moralalignmentMixinFields1 := moralalignmentMixin[1].Fields()
	_ = moralalignmentMixinFields1
	moralalignmentFields := schema.MoralAlignment{}.Fields()
	_ = moralalignmentFields
	// moralalignmentDescCreatedAt is the schema descriptor for created_at field.
	moralalignmentDescCreatedAt := moralalignmentMixinFields0[0].Descriptor()
	// moralalignment.DefaultCreatedAt holds the default value on creation for the created_at field.
	moralalignment.DefaultCreatedAt = moralalignmentDescCreatedAt.Default.(func() time.Time)
	// moralalignmentDescUpdatedAt is the schema descriptor for updated_at field.
	moralalignmentDescUpdatedAt := moralalignmentMixinFields0[1].Descriptor()
	// moralalignment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	moralalignment.DefaultUpdatedAt = moralalignmentDescUpdatedAt.Default.(func() time.Time)
	// moralalignment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	moralalignment.UpdateDefaultUpdatedAt = moralalignmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// moralalignmentDescNameEn is the schema descriptor for name_en field.
	moralalignmentDescNameEn := moralalignmentMixinFields1[0].Descriptor()
	// moralalignment.NameEnValidator is a validator for the "name_en" field. It is called by the builders before save.
	moralalignment.NameEnValidator = moralalignmentDescNameEn.Validators[0].(func(string) error)
	// moralalignmentDescID is the schema descriptor for id field.
	moralalignmentDescID := moralalignmentFields[0].Descriptor()
	// moralalignment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	moralalignment.IDValidator = moralalignmentDescID.Validators[0].(func(int) error)
	orderalignmentMixin := schema.OrderAlignment{}.Mixin()
	orderalignmentMixinFields0 := orderalignmentMixin[0].Fields()
	_ = orderalignmentMixinFields0
	orderalignmentMixinFields1 := orderalignmentMixin[1].Fields()
	_ = orderalignmentMixinFields1
	orderalignmentFields := schema.OrderAlignment{}.Fields()
	_ = orderalignmentFields
	// orderalignmentDescCreatedAt is the schema descriptor for created_at field.
	orderalignmentDescCreatedAt := orderalignmentMixinFields0[0].Descriptor()
	// orderalignment.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderalignment.DefaultCreatedAt = orderalignmentDescCreatedAt.Default.(func() time.Time)
	// orderalignmentDescUpdatedAt is the schema descriptor for updated_at field.
	orderalignmentDescUpdatedAt := orderalignmentMixinFields0[1].Descriptor()
	// orderalignment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderalignment.DefaultUpdatedAt = orderalignmentDescUpdatedAt.Default.(func() time.Time)
	// orderalignment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderalignment.UpdateDefaultUpdatedAt = orderalignmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderalignmentDescNameEn is the schema descriptor for name_en field.
	orderalignmentDescNameEn := orderalignmentMixinFields1[0].Descriptor()
	// orderalignment.NameEnValidator is a validator for the "name_en" field. It is called by the builders before save.
	orderalignment.NameEnValidator = orderalignmentDescNameEn.Validators[0].(func(string) error)
	// orderalignmentDescID is the schema descriptor for id field.
	orderalignmentDescID := orderalignmentFields[0].Descriptor()
	// orderalignment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	orderalignment.IDValidator = orderalignmentDescID.Validators[0].(func(int) error)
	servantMixin := schema.Servant{}.Mixin()
	servantMixinFields0 := servantMixin[0].Fields()
	_ = servantMixinFields0
	servantFields := schema.Servant{}.Fields()
	_ = servantFields
	// servantDescCreatedAt is the schema descriptor for created_at field.
	servantDescCreatedAt := servantMixinFields0[0].Descriptor()
	// servant.DefaultCreatedAt holds the default value on creation for the created_at field.
	servant.DefaultCreatedAt = servantDescCreatedAt.Default.(func() time.Time)
	// servantDescUpdatedAt is the schema descriptor for updated_at field.
	servantDescUpdatedAt := servantMixinFields0[1].Descriptor()
	// servant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	servant.DefaultUpdatedAt = servantDescUpdatedAt.Default.(func() time.Time)
	// servant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	servant.UpdateDefaultUpdatedAt = servantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// servantDescCollectionNo is the schema descriptor for collection_no field.
	servantDescCollectionNo := servantFields[1].Descriptor()
	// servant.CollectionNoValidator is a validator for the "collection_no" field. It is called by the builders before save.
	servant.CollectionNoValidator = servantDescCollectionNo.Validators[0].(func(int) error)
	// servantDescName is the schema descriptor for name field.
	servantDescName := servantFields[2].Descriptor()
	// servant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	servant.NameValidator = servantDescName.Validators[0].(func(string) error)
	// servantDescFace is the schema descriptor for face field.
	servantDescFace := servantFields[3].Descriptor()
	// servant.FaceValidator is a validator for the "face" field. It is called by the builders before save.
	servant.FaceValidator = servantDescFace.Validators[0].(func(string) error)
	// servantDescClassID is the schema descriptor for class_id field.
	servantDescClassID := servantFields[4].Descriptor()
	// servant.ClassIDValidator is a validator for the "class_id" field. It is called by the builders before save.
	servant.ClassIDValidator = servantDescClassID.Validators[0].(func(int) error)
	// servantDescAttributeID is the schema descriptor for attribute_id field.
	servantDescAttributeID := servantFields[5].Descriptor()
	// servant.AttributeIDValidator is a validator for the "attribute_id" field. It is called by the builders before save.
	servant.AttributeIDValidator = servantDescAttributeID.Validators[0].(func(int) error)
	// servantDescOrderAlignmentID is the schema descriptor for order_alignment_id field.
	servantDescOrderAlignmentID := servantFields[6].Descriptor()
	// servant.OrderAlignmentIDValidator is a validator for the "order_alignment_id" field. It is called by the builders before save.
	servant.OrderAlignmentIDValidator = servantDescOrderAlignmentID.Validators[0].(func(int) error)
	// servantDescMoralAlignmentID is the schema descriptor for moral_alignment_id field.
	servantDescMoralAlignmentID := servantFields[7].Descriptor()
	// servant.MoralAlignmentIDValidator is a validator for the "moral_alignment_id" field. It is called by the builders before save.
	servant.MoralAlignmentIDValidator = servantDescMoralAlignmentID.Validators[0].(func(int) error)
	// servantDescID is the schema descriptor for id field.
	servantDescID := servantFields[0].Descriptor()
	// servant.IDValidator is a validator for the "id" field. It is called by the builders before save.
	servant.IDValidator = servantDescID.Validators[0].(func(int) error)
	traitMixin := schema.Trait{}.Mixin()
	traitMixinFields0 := traitMixin[0].Fields()
	_ = traitMixinFields0
	traitMixinFields1 := traitMixin[1].Fields()
	_ = traitMixinFields1
	traitFields := schema.Trait{}.Fields()
	_ = traitFields
	// traitDescCreatedAt is the schema descriptor for created_at field.
	traitDescCreatedAt := traitMixinFields0[0].Descriptor()
	// trait.DefaultCreatedAt holds the default value on creation for the created_at field.
	trait.DefaultCreatedAt = traitDescCreatedAt.Default.(func() time.Time)
	// traitDescUpdatedAt is the schema descriptor for updated_at field.
	traitDescUpdatedAt := traitMixinFields0[1].Descriptor()
	// trait.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	trait.DefaultUpdatedAt = traitDescUpdatedAt.Default.(func() time.Time)
	// trait.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	trait.UpdateDefaultUpdatedAt = traitDescUpdatedAt.UpdateDefault.(func() time.Time)
	// traitDescNameEn is the schema descriptor for name_en field.
	traitDescNameEn := traitMixinFields1[0].Descriptor()
	// trait.NameEnValidator is a validator for the "name_en" field. It is called by the builders before save.
	trait.NameEnValidator = traitDescNameEn.Validators[0].(func(string) error)
	// traitDescID is the schema descriptor for id field.
	traitDescID := traitFields[0].Descriptor()
	// trait.IDValidator is a validator for the "id" field. It is called by the builders before save.
	trait.IDValidator = traitDescID.Validators[0].(func(int) error)
}
