// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koo-arch/servant-trait-filter-backend/ent/servant"
	"github.com/koo-arch/servant-trait-filter-backend/ent/trait"
)

// TraitCreate is the builder for creating a Trait entity.
type TraitCreate struct {
	config
	mutation *TraitMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (tc *TraitCreate) SetCreatedAt(t time.Time) *TraitCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TraitCreate) SetNillableCreatedAt(t *time.Time) *TraitCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TraitCreate) SetUpdatedAt(t time.Time) *TraitCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TraitCreate) SetNillableUpdatedAt(t *time.Time) *TraitCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetNameEn sets the "name_en" field.
func (tc *TraitCreate) SetNameEn(s string) *TraitCreate {
	tc.mutation.SetNameEn(s)
	return tc
}

// SetNameJa sets the "name_ja" field.
func (tc *TraitCreate) SetNameJa(s string) *TraitCreate {
	tc.mutation.SetNameJa(s)
	return tc
}

// AddServantIDs adds the "servants" edge to the Servant entity by IDs.
func (tc *TraitCreate) AddServantIDs(ids ...int) *TraitCreate {
	tc.mutation.AddServantIDs(ids...)
	return tc
}

// AddServants adds the "servants" edges to the Servant entity.
func (tc *TraitCreate) AddServants(s ...*Servant) *TraitCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tc.AddServantIDs(ids...)
}

// Mutation returns the TraitMutation object of the builder.
func (tc *TraitCreate) Mutation() *TraitMutation {
	return tc.mutation
}

// Save creates the Trait in the database.
func (tc *TraitCreate) Save(ctx context.Context) (*Trait, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TraitCreate) SaveX(ctx context.Context) *Trait {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TraitCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TraitCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TraitCreate) defaults() {
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := trait.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := trait.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TraitCreate) check() error {
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Trait.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Trait.updated_at"`)}
	}
	if _, ok := tc.mutation.NameEn(); !ok {
		return &ValidationError{Name: "name_en", err: errors.New(`ent: missing required field "Trait.name_en"`)}
	}
	if v, ok := tc.mutation.NameEn(); ok {
		if err := trait.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "Trait.name_en": %w`, err)}
		}
	}
	if _, ok := tc.mutation.NameJa(); !ok {
		return &ValidationError{Name: "name_ja", err: errors.New(`ent: missing required field "Trait.name_ja"`)}
	}
	return nil
}

func (tc *TraitCreate) sqlSave(ctx context.Context) (*Trait, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TraitCreate) createSpec() (*Trait, *sqlgraph.CreateSpec) {
	var (
		_node = &Trait{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(trait.Table, sqlgraph.NewFieldSpec(trait.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(trait.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(trait.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := tc.mutation.NameEn(); ok {
		_spec.SetField(trait.FieldNameEn, field.TypeString, value)
		_node.NameEn = value
	}
	if value, ok := tc.mutation.NameJa(); ok {
		_spec.SetField(trait.FieldNameJa, field.TypeString, value)
		_node.NameJa = value
	}
	if nodes := tc.mutation.ServantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   trait.ServantsTable,
			Columns: trait.ServantsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TraitCreateBulk is the builder for creating many Trait entities in bulk.
type TraitCreateBulk struct {
	config
	err      error
	builders []*TraitCreate
}

// Save creates the Trait entities in the database.
func (tcb *TraitCreateBulk) Save(ctx context.Context) ([]*Trait, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Trait, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TraitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TraitCreateBulk) SaveX(ctx context.Context) []*Trait {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TraitCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TraitCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
