// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/koo-arch/servant-trait-filter-backend/ent/trait"
)

// Trait is the model entity for the Trait schema.
type Trait struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// NameEn holds the value of the "name_en" field.
	NameEn string `json:"name_en,omitempty"`
	// NameJa holds the value of the "name_ja" field.
	NameJa string `json:"name_ja,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TraitQuery when eager-loading is set.
	Edges        TraitEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TraitEdges holds the relations/edges for other nodes in the graph.
type TraitEdges struct {
	// Servants holds the value of the servants edge.
	Servants []*Servant `json:"servants,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ServantsOrErr returns the Servants value or an error if the edge
// was not loaded in eager-loading.
func (e TraitEdges) ServantsOrErr() ([]*Servant, error) {
	if e.loadedTypes[0] {
		return e.Servants, nil
	}
	return nil, &NotLoadedError{edge: "servants"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Trait) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case trait.FieldID:
			values[i] = new(sql.NullInt64)
		case trait.FieldNameEn, trait.FieldNameJa:
			values[i] = new(sql.NullString)
		case trait.FieldCreatedAt, trait.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Trait fields.
func (t *Trait) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case trait.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case trait.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				t.CreatedAt = value.Time
			}
		case trait.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				t.UpdatedAt = value.Time
			}
		case trait.FieldNameEn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_en", values[i])
			} else if value.Valid {
				t.NameEn = value.String
			}
		case trait.FieldNameJa:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_ja", values[i])
			} else if value.Valid {
				t.NameJa = value.String
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Trait.
// This includes values selected through modifiers, order, etc.
func (t *Trait) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryServants queries the "servants" edge of the Trait entity.
func (t *Trait) QueryServants() *ServantQuery {
	return NewTraitClient(t.config).QueryServants(t)
}

// Update returns a builder for updating this Trait.
// Note that you need to call Trait.Unwrap() before calling this method if this Trait
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Trait) Update() *TraitUpdateOne {
	return NewTraitClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Trait entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Trait) Unwrap() *Trait {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Trait is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Trait) String() string {
	var builder strings.Builder
	builder.WriteString("Trait(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("created_at=")
	builder.WriteString(t.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(t.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name_en=")
	builder.WriteString(t.NameEn)
	builder.WriteString(", ")
	builder.WriteString("name_ja=")
	builder.WriteString(t.NameJa)
	builder.WriteByte(')')
	return builder.String()
}

// Traits is a parsable slice of Trait.
type Traits []*Trait
