// Code generated by ent, DO NOT EDIT.

package orderalignment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the orderalignment type in the database.
	Label = "order_alignment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldNameEn holds the string denoting the name_en field in the database.
	FieldNameEn = "name_en"
	// FieldNameJa holds the string denoting the name_ja field in the database.
	FieldNameJa = "name_ja"
	// EdgeAscensions holds the string denoting the ascensions edge name in mutations.
	EdgeAscensions = "ascensions"
	// Table holds the table name of the orderalignment in the database.
	Table = "order_alignments"
	// AscensionsTable is the table that holds the ascensions relation/edge.
	AscensionsTable = "ascensions"
	// AscensionsInverseTable is the table name for the Ascension entity.
	// It exists in this package in order to avoid circular dependency with the "ascension" package.
	AscensionsInverseTable = "ascensions"
	// AscensionsColumn is the table column denoting the ascensions relation/edge.
	AscensionsColumn = "order_alignment_id"
)

// Columns holds all SQL columns for orderalignment fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldNameEn,
	FieldNameJa,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameEnValidator is a validator for the "name_en" field. It is called by the builders before save.
	NameEnValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the OrderAlignment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNameEn orders the results by the name_en field.
func ByNameEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameEn, opts...).ToFunc()
}

// ByNameJa orders the results by the name_ja field.
func ByNameJa(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameJa, opts...).ToFunc()
}

// ByAscensionsCount orders the results by ascensions count.
func ByAscensionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAscensionsStep(), opts...)
	}
}

// ByAscensions orders the results by ascensions terms.
func ByAscensions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAscensionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAscensionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AscensionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AscensionsTable, AscensionsColumn),
	)
}
