// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Ascension is the predicate function for ascension builders.
type Ascension func(*sql.Selector)

// Attribute is the predicate function for attribute builders.
type Attribute func(*sql.Selector)

// Class is the predicate function for class builders.
type Class func(*sql.Selector)

// MoralAlignment is the predicate function for moralalignment builders.
type MoralAlignment func(*sql.Selector)

// OrderAlignment is the predicate function for orderalignment builders.
type OrderAlignment func(*sql.Selector)

// Servant is the predicate function for servant builders.
type Servant func(*sql.Selector)

// Trait is the predicate function for trait builders.
type Trait func(*sql.Selector)
